const objectCalendar = {
  type: 'object',
  properties: {
    equipe_ssid: { type: 'string' },
    professor_ssid: { type: 'string' },
    shortname: { type: 'string' },
    disciplina: { type: 'string' },
    turma: { type: 'string' },
    login_prof: { type: 'string' },
    nome_professor: { type: 'string' },
    nr_dia_semana: { type: 'number' },
    dia_semana: { type: 'string' },
    hora_inicio: { type: 'string' },
    hora_termino: { type: 'string' },
    data: { type: 'string', format: 'date' },
    url: { type: 'string' },
    tipo: { type: 'string' },
    ativo: { type: 'number' },
    team_url: { type: 'string' },
    idmediastream: { type: 'string' },
    linkmedia: { type: 'string' },
    numero_semana: { type: 'number' },
  },
  required: [
    'equipe_ssid',
    'professor_ssid',
    'shortname',
    'disciplina',
    'login_prof',
    'nome_professor',
    'nr_dia_semana',
    'dia_semana',
    'hora_inicio',
    'hora_termino',
    'data',
    'url',
    'tipo',
    'ativo',
    'numero_semana',
  ],
};

module.exports = objectCalendar;
